### ISSUE TITLE
스크린샷을 추가하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by hannut91** [haechan07/GradeCalculator#1]
사용하는 예제를 스크린샷으로 첨부하면, 어떤 프로젝트인지 이해하기 쉬울 것 같습니다!

먼저 스크린샷을 첨부하고, 더 나아가서 GIF로 움직이는 것을 보여주면 더 좋을 것 같아요.

제가 작성했던 README를 참고해보시면 좋을 것 같습니다

* https://github.com/hannut91/vs-code-wiki

**Comment by haechan07** [comment]
촬영은 막 했습니다.
리드미를 수정하는데 시간이 좀 들거같네요 :(

**Comment by haechan07** [comment]
수정했습니다 :)
