### ISSUE TITLE
[건의] 실행파일을 만들어 배포해보면 어떨까요?

### ISSUE THREAD

**Issue by roeniss** [haechan07/GradeCalculator#2]
개발자가 아닌 사람에게는 kt 파일을 실행하는게 상당히 부담스러울 수 있습니다.

(우선적으로) 윈도우 유저들을 위해 GradeCalculator.exe 를 만들어서, 깃헙 Release 섹션을 통해 배포해보면 어떨까요?

코틀린쪽은 잘 모르지만, 파이썬에는 pyinstaller가 비슷한 기능을 하고 있습니다. 감이 안잡힌다면 그쪽으로 찾아보시는 것도 좋을 것 같습니다.

**Comment by haechan07** [comment]
pyinstaller는 쓸줄 압니다만 코틀린쪽은 워낙에 초보라 저도 .kt 파일을 실행 못합니다.(IDE에서나 여는...)
실행파일을 만드는 걸 최우선 목표로 하고 있습니다.
(일단 그 전에 시험을 마쳐야겠지만)
관심 가져주셔서 감사하고 늦은 답변 죄송합니다.

**Comment by haechan07** [comment]
모듈 변경을 통해 네이티브 .exe 파일을 만드는데에는 성공했습니다. 이제 스트링빌더를 출력하고 바로 꺼지지 않게 하거나 파일 생성 형태로 좀 변형하면 될 듯 합니다 :)

**Comment by haechan07** [comment]
v1.2를 Release 했으며 그곳에 .exe파일을 올렸습니다. 이슈는 닫겠습니다. 감사합니다.
